//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GROCERY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GROCERYEntities : DbContext
    {
        public GROCERYEntities()
            : base("name=GROCERYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AD> ADS { get; set; }
        public virtual DbSet<AREA> AREAS { get; set; }
        public virtual DbSet<BARCODESTest> BARCODESTests { get; set; }
        public virtual DbSet<BRANCH> BRANCHES { get; set; }
        public virtual DbSet<BRAND> BRANDS { get; set; }
        public virtual DbSet<CATEGORy> CATEGORIES { get; set; }
        public virtual DbSet<COUPON> COUPONS { get; set; }
        public virtual DbSet<GROUP> GROUPS { get; set; }
        public virtual DbSet<ITEMINFO> ITEMINFOes { get; set; }
        public virtual DbSet<ORDER_PRODUCTS> ORDER_PRODUCTS { get; set; }
        public virtual DbSet<ORDER_STATUSES> ORDER_STATUSES { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<PACKAGE_PRODUCTS> PACKAGE_PRODUCTS { get; set; }
        public virtual DbSet<PACKAGE> PACKAGES { get; set; }
        public virtual DbSet<PAYMENT_MODES> PAYMENT_MODES { get; set; }
        public virtual DbSet<PRODUCT_BRANDS> PRODUCT_BRANDS { get; set; }
        public virtual DbSet<PRODUCT_COLORS> PRODUCT_COLORS { get; set; }
        public virtual DbSet<PRODUCT_FLAVORS> PRODUCT_FLAVORS { get; set; }
        public virtual DbSet<PRODUCT_IMAGES> PRODUCT_IMAGES { get; set; }
        public virtual DbSet<PRODUCT_LEVELS> PRODUCT_LEVELS { get; set; }
        public virtual DbSet<PRODUCT_PACKINGS> PRODUCT_PACKINGS { get; set; }
        public virtual DbSet<PRODUCT_TAGS> PRODUCT_TAGS { get; set; }
        public virtual DbSet<PRODUCT_TYPES> PRODUCT_TYPES { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<ProductTest> ProductTests { get; set; }
        public virtual DbSet<PS000> PS000 { get; set; }
        public virtual DbSet<SM> SMS { get; set; }
        public virtual DbSet<SMS_TYPES> SMS_TYPES { get; set; }
        public virtual DbSet<STOCK> STOCKs { get; set; }
        public virtual DbSet<SUB_CATEGORIES> SUB_CATEGORIES { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TEMP_CUSTOMERS> TEMP_CUSTOMERS { get; set; }
        public virtual DbSet<USER_ADDRESSES> USER_ADDRESSES { get; set; }
        public virtual DbSet<USER_FAVOURITES> USER_FAVOURITES { get; set; }
        public virtual DbSet<USER_TYPES> USER_TYPES { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<VENDOR_BRANCHES> VENDOR_BRANCHES { get; set; }
        public virtual DbSet<VENDOR> VENDORS { get; set; }
        public virtual DbSet<BarcodeNewTest> BarcodeNewTests { get; set; }
        public virtual DbSet<BARCODE> BARCODES { get; set; }
        public virtual DbSet<PS000Test> PS000Test { get; set; }
        public virtual DbSet<TEST> TESTs { get; set; }
    }
}
